# Generated by Django 2.0.9 on 2018-12-22 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
